batch_size: 2
config: ./configs/baseline.yaml
dataset: phoenix14
dataset_info:
  dataset_root: ./dataset/phoenix2014/phoenix-2014-multisigner
  dict_path: ./preprocess/phoenix2014/gloss_dict.npy
  evaluation_dir: ./evaluation/slr_eval
  evaluation_prefix: phoenix2014-groundtruth
decode_mode: beam
device: 0,1,2
eval_interval: 1
evaluate_tool: sclite
feeder: dataset.dataloader.BaseFeeder
feeder_args:
  folder_path: E:\CSAWS\CSAW-S\CsawS\anonymized_dataset
  mean: 0.0
  mode: train
  prefix: ''
  std: 1.0
ignore_weights: []
load_checkpoints: null
load_weights: null
log_interval: 50
loss_weights:
  ConvCTC: 1.0
  Dist: 10.0
  SeqCTC: 1.0
model: slr_network.SLRModel
model_args:
  c2d_type: resnet18
  conv_type: 2
  num_classes: 1296
  use_bn: 1
num_epoch: 80
num_worker: 10
optimizer_args:
  base_lr: 0.0001
  learning_ratio: 1
  nesterov: false
  optimizer: Adam
  start_epoch: 1
  step:
  - 40
  - 60
  weight_decay: 0.0001
phase: train
print_log: true
random_fix: true
random_seed: 0
save_interval: 5
test_batch_size: 8
work_dir: ./work_dir/baseline_res18/
